FROM pimcore/pimcore:PHP8.1-supervisord

RUN set -eux; \
    apt update -y; \
    apt install -y vim netcat iputils-ping net-tools cron; \
    rm -rf /var/lib/apt/lists/*; \
    usermod -u 1000 www-data; \
    groupmod -g 1000 www-data; 

COPY --chown=www-data:www-data /console /var/www/html/bin/console
RUN chmod +x /var/www/html/bin/console

COPY /supervisord/supervisord.conf /etc/supervisor/conf.d/pimcore.conf